// app/src/app/components/barcode/barcode.component.ts
import { Component, EventEmitter, HostListener, Output } from '@angular/core';

@Component({
  selector: 'app-barcode',
  template: '',
  standalone: true
})
export class BarcodeComponent {
  @Output() scanned = new EventEmitter<string>();

  private buffer = '';

  @HostListener('document:keydown', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      if (this.buffer.trim() !== '') {
        this.scanned.emit(this.buffer.toUpperCase());
        this.buffer = '';
      }
    } else {
      this.buffer += event.key;
    }
  }
}

// app/src/components/Barcode.tsx
import { useEffect, useRef } from 'react';

interface BarcodeProps {
  onScanned: (code: string) => void;
}

export default function Barcode({ onScanned }: BarcodeProps) {
  const bufferRef = useRef('');

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Enter') {
        if (bufferRef.current.trim() !== '') {
          onScanned(bufferRef.current.toUpperCase());
          bufferRef.current = '';
        }
      } else {
        bufferRef.current += event.key;
      }
    };
    document.addEventListener('keydown', handleKeyDown);
    return () => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [onScanned]);

  return null;
}
